version: "3.9"
services:
  config_server:
    build: "config/."
    command: ["bash", "-c", "cd /home; git clone https://github.com/AdrianNMS/config_server.git; cd config_server; mvn install; mvn spring-boot:run"]
    ports:
      - "8888:8888"
    expose:
      - "8888"

  eureka-server:
    build: "config/."
    command: ["bash", "-c", "cd /home; git clone https://github.com/AdrianNMS/eureka-server.git; cd eureka-server; mvn install; mvn spring-boot:run"]
    ports:
      - "8761:8761"
    expose:
      - "8761"
    depends_on:
      - config_server
  api-gateway:
    build: "config/."
    command: ["bash", "-c", "cd /home; git clone https://github.com/AdrianNMS/api-gateway.git; cd api-gateway; mvn install; mvn spring-boot:run"]
    ports:
      - "8850:8850"
    expose:
      - "8850"
    depends_on:
      - config_server
      - eureka-server
  person:
    build: "microservice/."
    command: ["bash", "-c", "cd /home; git clone https://github.com/AdrianNMS/person.git; cd person; mvn install; mvn spring-boot:run"]
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - config_server
      - eureka-server
 
  
  # docker-compose up -d
  # wget 172.29.0.2:8888/person/default funciona
  # wget config_server:8888/person/default no funciona

  # docker build -t test .

  # docker run --name prueba -p 8080:8080 test

  # mvn install 

  # mvn spring-boot:run 
